# Generated by Django 4.2.16 on 2024-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
